#!/usr/bin/env python3
"""
Create Theme Script - Generate complete Odoo website theme modules

This script creates a production-ready theme module with all necessary files
based on patterns discovered from 40+ real-world theme implementations.

Usage:
    python create_theme.py <theme_name> <output_path> [options]

Options:
    --version=<ver>     Odoo version (14-19), default: 17
    --colors=<colors>   Comma-separated 5 colors (#hex), default: blue palette
    --font=<font>       Primary font family, default: "IBM Plex Sans"
    --header=<tpl>      Header template (default/hamburger/centered)
    --footer=<tpl>      Footer template (default/headline/minimalist)
    --author=<name>     Author name, default: "TaqaTechno"

Author: TAQAT Techno
Version: 2.0.0
"""

import os
import sys
import re
import argparse
from pathlib import Path
from datetime import datetime


# Default color palette (Relief Center inspired)
DEFAULT_COLORS = {
    'color_1': '#207AB7',  # Primary brand blue
    'color_2': '#FB9F54',  # Secondary orange
    'color_3': '#F6F4F0',  # Light backgrounds
    'color_4': '#FFFFFF',  # White base
    'color_5': '#191A19',  # Dark text
}

# Popular font configurations
FONT_CONFIGS = {
    'IBM Plex Sans': 'IBM+Plex+Sans:100,200,300,400,500,600,700&display=swap',
    'Inter': 'Inter:wght@300;400;500;600;700&display=swap',
    'Roboto': 'Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i',
    'Open Sans': 'Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i',
    'Poppins': 'Poppins:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i',
    'Montserrat': 'Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i',
    'Cairo': 'Cairo:200,300,400,500,600,700,800,900,1000&display=swap',
    'Almarai': 'Almarai:300,400,700,900&display=swap',
}


def to_snake_case(name):
    """Convert name to snake_case"""
    name = re.sub(r'[-\s]+', '_', name)
    name = re.sub(r'[^\w_]', '', name)
    name = name.lower()
    return name


def to_display_name(name):
    """Convert snake_case to Display Name"""
    return ' '.join(word.capitalize() for word in name.split('_'))


def get_bootstrap_version(odoo_version):
    """Get Bootstrap version for Odoo version"""
    if odoo_version in [14, 15]:
        return '4.5.0'
    return '5.1.3'


def create_directory_structure(base_path, theme_name):
    """Create complete directory structure"""
    dirs = [
        '',
        'security',
        'data',
        'data/pages',
        'views',
        'views/layout',
        'views/snippets',
        'static',
        'static/description',
        'static/src',
        'static/src/scss',
        'static/src/js',
        'static/src/img',
    ]

    theme_path = Path(base_path) / f'theme_{theme_name}'

    for d in dirs:
        dir_path = theme_path / d
        dir_path.mkdir(parents=True, exist_ok=True)

    return theme_path


def generate_manifest(config):
    """Generate __manifest__.py content"""
    return f'''# -*- encoding: utf-8 -*-
{{
    'name': 'Theme {config["display_name"]}',
    'version': '{config["odoo_version"]}.0.1.0.0',
    'summary': '{config["display_name"]} - Professional Odoo Website Theme',
    'description': """
        {config["display_name"]} Theme
        {"=" * len(config["display_name"])}======

        A professional, responsive website theme for Odoo {config["odoo_version"]}.

        Features:
        - Bootstrap {config["bootstrap_version"]}
        - Responsive design
        - Custom color palette
        - Google Fonts integration
        - publicWidget interactions
        - Multi-website support

        Generated by TAQAT Techno Plugin
    """,
    'category': 'Website/Theme',
    'author': '{config["author"]}',
    'website': 'https://www.taqatechno.com/',
    'support': 'info@taqatechno.com',
    'license': 'LGPL-3',
    'depends': ['website'],
    'data': [
        'security/ir.model.access.csv',
        'data/assets.xml',
        'views/layout/header.xml',
        'views/layout/footer.xml',
        'views/layout/templates.xml',
        'views/snippets/custom_snippets.xml',
        'data/menu.xml',
        'data/pages/home_page.xml',
        'data/pages/aboutus_page.xml',
        'data/pages/contactus_page.xml',
        'data/pages/services_page.xml',
    ],
    'assets': {{
        'web._assets_primary_variables': [
            'theme_{config["theme_name"]}/static/src/scss/primary_variables.scss',
        ],
        'web._assets_frontend_helpers': [
            ('prepend', 'theme_{config["theme_name"]}/static/src/scss/bootstrap_overridden.scss'),
        ],
        'web.assets_frontend': [
            'theme_{config["theme_name"]}/static/src/scss/theme.scss',
            'theme_{config["theme_name"]}/static/src/js/theme.js',
        ],
        'website.assets_wysiwyg': [
            'theme_{config["theme_name"]}/static/src/js/snippets_options.js',
        ],
    }},
    'images': [
        'static/description/cover.png',
        'static/description/screenshot.png',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}}
'''


def generate_init_py():
    """Generate __init__.py content"""
    return '''# -*- coding: utf-8 -*-
# Theme module - no Python models required
'''


def generate_security_csv():
    """Generate security/ir.model.access.csv content"""
    return '''id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
'''


def generate_primary_variables(config):
    """Generate primary_variables.scss content"""
    font_url = FONT_CONFIGS.get(config['font'], FONT_CONFIGS['IBM Plex Sans'])

    return f'''// ===================================================================
// Theme: {config["display_name"]}
// Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}
// Author: {config["author"]}
// ===================================================================

// === Typography Hierarchy ===
$o-theme-h1-font-size-multiplier: (64 / 16); // 4rem - Hero text
$o-theme-h2-font-size-multiplier: (48 / 16); // 3rem - Section headers
$o-theme-h3-font-size-multiplier: (32 / 16); // 2rem - Sub-section headers
$o-theme-h4-font-size-multiplier: (28 / 16); // 1.75rem - Card headers
$o-theme-h5-font-size-multiplier: (24 / 16); // 1.5rem - Small headers
$o-theme-h6-font-size-multiplier: (18 / 16); // 1.125rem - Captions

$o-theme-headings-font-weight: 700;
$o-theme-font-weight-normal: 400;
$o-theme-font-weight-medium: 500;
$o-theme-font-weight-semibold: 600;
$o-theme-font-weight-bold: 700;

// === Website Values Palette ===
$o-website-values-palettes: (
    (
        'color-palettes-name': '{config["palette_name"]}',

        // Typography
        'font': '{config["font"]}',
        'headings-font': '{config["font"]}',
        'navbar-font': '{config["font"]}',
        'buttons-font': '{config["font"]}',
        'headings-line-height': 1.3,
        'line-height-base': 1.6,

        // Header
        'header-template': '{config["header_template"]}',
        'header-links-style': 'default',
        'hamburger-position': 'right',
        'logo-height': 3rem,
        'fixed-logo-height': 2rem,

        // Buttons
        'btn-padding-y': 0.75rem,
        'btn-padding-x': 2rem,
        'btn-padding-y-sm': 0.5rem,
        'btn-padding-x-sm': 1.5rem,
        'btn-padding-y-lg': 1rem,
        'btn-padding-x-lg': 3rem,
        'btn-border-radius': 0.5rem,
        'btn-border-radius-sm': 0.25rem,
        'btn-border-radius-lg': 0.75rem,
        'btn-font-weight': 500,

        // Inputs
        'input-padding-y': 0.75rem,
        'input-padding-x': 1rem,
        'input-border-radius': 0.5rem,

        // Footer
        'footer-template': '{config["footer_template"]}',
        'footer-scrolltop': true,

        // Links
        'link-underline': 'never',
    ),
);

// === Color Palette (Semantic Structure) ===
// o-color-1: Primary brand color
// o-color-2: Secondary/accent color
// o-color-3: Light backgrounds
// o-color-4: White/body base
// o-color-5: Dark text/headings
$o-color-palettes: map-merge($o-color-palettes, (
    '{config["palette_name"]}': (
        'o-color-1': {config["colors"]["color_1"]},
        'o-color-2': {config["colors"]["color_2"]},
        'o-color-3': {config["colors"]["color_3"]},
        'o-color-4': {config["colors"]["color_4"]},
        'o-color-5': {config["colors"]["color_5"]},
        'menu': 1,
        'footer': 1,
        'copyright': 5,
    ),
));

// === Font Configuration ===
$o-theme-font-configs: map-merge($o-theme-font-configs, (
    '{config["font"]}': (
        'family': ('{config["font"]}', sans-serif),
        'url': '{font_url}',
        'properties': (
            'base': (
                'font-size-base': 1rem,
                'line-height-base': 1.6,
            ),
        ),
    ),
));

// === Extended Color System ===
$o-white: #FFFFFF !default;
$o-black: {config["colors"]["color_5"]} !default;
$o-success: #28a745 !default;
$o-info: #17a2b8 !default;
$o-warning: #ffc107 !default;
$o-danger: #dc3545 !default;

// Gray scale
$o-gray-100: #F9FAFB !default;
$o-gray-200: #eeeeee !default;
$o-gray-300: #d8dadd !default;
$o-gray-400: #9a9ca5 !default;
$o-gray-500: #7c7f89 !default;
$o-gray-600: #5f636f !default;
$o-gray-700: #374151 !default;
$o-gray-800: #1F2937 !default;
$o-gray-900: #111827 !default;

// === Background Shapes ===
$o-bg-shapes: change-shape-colors-mapping('web_editor', 'Wavy/21', (2: 1));
'''


def generate_bootstrap_overridden(config):
    """Generate bootstrap_overridden.scss content"""
    return f'''// ===================================================================
// Bootstrap Overrides for {config["display_name"]}
// Only override Bootstrap vars not available in Odoo variables
// ===================================================================

// Spacing
$spacer: 1rem !default;

// Border radius
$border-radius: 0.5rem !default;
$border-radius-sm: 0.25rem !default;
$border-radius-lg: 0.75rem !default;

// Shadows
$box-shadow-sm: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075) !default;
$box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15) !default;
$box-shadow-lg: 0 1rem 3rem rgba(0, 0, 0, 0.175) !default;

// Transitions
$transition-base: all 0.3s ease-in-out !default;
$transition-fade: opacity 0.15s linear !default;
'''


def generate_theme_scss(config):
    """Generate theme.scss content"""
    return f'''// ===================================================================
// Theme Styles for {config["display_name"]}
// Custom styles that use the theme variables
// ===================================================================

// === Section Spacing ===
.section-padding {{
    padding-top: 5rem;
    padding-bottom: 5rem;
}}

.section-padding-sm {{
    padding-top: 3rem;
    padding-bottom: 3rem;
}}

// === Hero Section ===
.s_hero {{
    min-height: 600px;
    display: flex;
    align-items: center;
}}

// === Feature Cards ===
.card {{
    transition: transform 0.3s ease, box-shadow 0.3s ease;

    &:hover {{
        transform: translateY(-5px);
        box-shadow: 0 1rem 3rem rgba(0, 0, 0, 0.175);
    }}
}}

// === Animations ===
.animate-on-scroll {{
    opacity: 0;
    transform: translateY(30px);
    transition: opacity 0.6s ease, transform 0.6s ease;

    &.animated {{
        opacity: 1;
        transform: translateY(0);
    }}
}}

// === Lazy Load Images ===
img.lazy-load {{
    opacity: 0;
    transition: opacity 0.3s ease;

    &.loaded {{
        opacity: 1;
    }}
}}

// === Custom Utilities ===
.text-gradient {{
    background: linear-gradient(135deg, var(--o-color-1) 0%, var(--o-color-2) 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}}

// === Responsive Adjustments ===
@media (max-width: 991.98px) {{
    .section-padding {{
        padding-top: 3rem;
        padding-bottom: 3rem;
    }}

    .s_hero {{
        min-height: auto;
        padding-top: 4rem;
        padding-bottom: 4rem;
    }}
}}

@media (max-width: 767.98px) {{
    .section-padding {{
        padding-top: 2rem;
        padding-bottom: 2rem;
    }}
}}
'''


def generate_theme_js(config):
    """Generate theme.js content"""
    theme_class = ''.join(word.capitalize() for word in config['theme_name'].split('_'))

    return f'''/** @odoo-module **/

import publicWidget from "@web/legacy/js/public/public_widget";

/**
 * Animate On Scroll Widget
 * Uses IntersectionObserver to add animation classes when elements enter viewport
 */
publicWidget.registry.{theme_class}AnimateOnScroll = publicWidget.Widget.extend({{
    selector: '.animate-on-scroll',
    disabledInEditableMode: false,

    /**
     * @override
     */
    start: function () {{
        // Only initialize animations in read mode
        if (!this.editableMode) {{
            this._initAnimationObserver();
        }}
        return this._super.apply(this, arguments);
    }},

    /**
     * @override - CRITICAL: Clean up observers to prevent memory leaks
     */
    destroy: function () {{
        if (this.animationObserver) {{
            this.animationObserver.disconnect();
        }}
        return this._super.apply(this, arguments);
    }},

    /**
     * Initialize IntersectionObserver for scroll animations
     * @private
     */
    _initAnimationObserver: function () {{
        this.animationObserver = new IntersectionObserver(
            (entries) => {{
                entries.forEach((entry) => {{
                    entry.target.classList.toggle('animated', entry.isIntersecting);
                }});
            }},
            {{ threshold: 0.1 }}
        );

        document.querySelectorAll('.animate-on-scroll').forEach((el) => {{
            this.animationObserver.observe(el);
        }});
    }},
}});

/**
 * Smooth Scroll Widget
 * Handles smooth scrolling for anchor links
 */
publicWidget.registry.{theme_class}SmoothScroll = publicWidget.Widget.extend({{
    selector: 'a[href^="#"]',
    events: {{
        'click': '_onAnchorClick',
    }},

    /**
     * Handle click on anchor links
     * @private
     * @param {{Event}} ev
     */
    _onAnchorClick: function (ev) {{
        // Don't run in edit mode
        if (this.editableMode) return;

        const href = this.$el.attr('href');
        if (href && href.length > 1) {{
            const target = document.querySelector(href);
            if (target) {{
                ev.preventDefault();
                target.scrollIntoView({{
                    behavior: 'smooth',
                    block: 'start',
                }});
            }}
        }}
    }},
}});

/**
 * Lazy Image Load Widget
 * Uses native lazy loading with fallback
 */
publicWidget.registry.{theme_class}LazyLoad = publicWidget.Widget.extend({{
    selector: 'img.lazy-load',

    /**
     * @override
     */
    start: function () {{
        if (!this.editableMode) {{
            this._initLazyLoad();
        }}
        return this._super.apply(this, arguments);
    }},

    /**
     * @override
     */
    destroy: function () {{
        if (this.lazyObserver) {{
            this.lazyObserver.disconnect();
        }}
        return this._super.apply(this, arguments);
    }},

    /**
     * Initialize lazy loading
     * @private
     */
    _initLazyLoad: function () {{
        this.lazyObserver = new IntersectionObserver(
            (entries) => {{
                entries.forEach((entry) => {{
                    if (entry.isIntersecting) {{
                        const img = entry.target;
                        if (img.dataset.src) {{
                            img.src = img.dataset.src;
                            img.classList.add('loaded');
                        }}
                        this.lazyObserver.unobserve(img);
                    }}
                }});
            }},
            {{ threshold: 0.1, rootMargin: '50px' }}
        );

        this.lazyObserver.observe(this.el);
    }},
}});

export default {{
    AnimateOnScroll: publicWidget.registry.{theme_class}AnimateOnScroll,
    SmoothScroll: publicWidget.registry.{theme_class}SmoothScroll,
    LazyLoad: publicWidget.registry.{theme_class}LazyLoad,
}};
'''


def generate_snippets_options_js(config):
    """Generate snippets_options.js content"""
    theme_class = ''.join(word.capitalize() for word in config['theme_name'].split('_'))

    return f'''/** @odoo-module **/

/**
 * Snippet Options for {config["display_name"]} Theme
 *
 * Add custom snippet options here when creating new snippets.
 * This file is loaded in the website builder context.
 */

// Example snippet option (uncomment and customize when needed):
// import options from "@web_editor/js/editor/snippets.options";
//
// options.registry.{theme_class}CustomOption = options.Class.extend({{
//     /**
//      * Add custom item to snippet
//      */
//     addItem: function(previewMode, widgetValue, params) {{
//         const $lastItem = this.$target.find('.item').last();
//         if ($lastItem.length) {{
//             $lastItem.clone().appendTo(this.$target.find('.items-container'));
//         }}
//     }},
// }});
'''


def generate_assets_xml(config):
    """Generate data/assets.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data>
        <!-- Theme assets are configured in __manifest__.py -->
        <!-- This file can be used for additional asset configurations -->

        <!-- Example: Add external library
        <record id="theme_{config["theme_name"]}_external_lib" model="ir.asset">
            <field name="name">External Library</field>
            <field name="bundle">web.assets_frontend</field>
            <field name="path">theme_{config["theme_name"]}/static/src/lib/external.js</field>
        </record>
        -->
    </data>
</odoo>
'''


def generate_menu_xml(config):
    """Generate data/menu.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data>
        <record id="menu_home" model="theme.website.menu">
            <field name="name">Home</field>
            <field name="url">/</field>
            <field name="sequence" type="int">10</field>
        </record>

        <record id="menu_about" model="theme.website.menu">
            <field name="name">About</field>
            <field name="url">/aboutus</field>
            <field name="sequence" type="int">20</field>
        </record>

        <record id="menu_services" model="theme.website.menu">
            <field name="name">Services</field>
            <field name="url">/services</field>
            <field name="sequence" type="int">30</field>
        </record>

        <record id="menu_contact" model="theme.website.menu">
            <field name="name">Contact</field>
            <field name="url">/contactus</field>
            <field name="sequence" type="int">40</field>
        </record>
    </data>
</odoo>
'''


def generate_header_xml(config):
    """Generate views/layout/header.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data>
        <!-- Header customization template -->
        <template id="header_custom" inherit_id="website.layout" name="{config['display_name']} Header">
            <xpath expr="//header" position="attributes">
                <attribute name="class" add="theme-{config['theme_name']}-header" separator=" "/>
            </xpath>
        </template>
    </data>
</odoo>
'''


def generate_footer_xml(config):
    """Generate views/layout/footer.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data>
        <!-- Footer customization template -->
        <template id="footer_custom" inherit_id="website.layout" name="{config['display_name']} Footer">
            <xpath expr="//footer" position="attributes">
                <attribute name="class" add="theme-{config['theme_name']}-footer" separator=" "/>
            </xpath>
        </template>
    </data>
</odoo>
'''


def generate_templates_xml(config):
    """Generate views/layout/templates.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data>
        <!-- Base layout customization -->
        <template id="layout_custom" inherit_id="website.layout" name="{config['display_name']} Layout">
            <xpath expr="//head" position="inside">
                <meta name="theme-name" content="{config['display_name']}"/>
                <meta name="theme-version" content="{config['odoo_version']}.0.1.0.0"/>
            </xpath>
        </template>
    </data>
</odoo>
'''


def generate_snippets_xml(config):
    """Generate views/snippets/custom_snippets.xml content"""
    # Use different XPath based on Odoo version
    if config['odoo_version'] >= 18:
        xpath_target = '//div[@id="snippet_structure"]/*[1]'
        group_attr = '\n                              group="custom"'
    else:
        xpath_target = '//div[@id="snippet_effect"]//t[@t-snippet][last()]'
        group_attr = ''

    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data>
        <!-- Custom snippet template -->
        <template id="s_{config['theme_name']}_cta" name="{config['display_name']} CTA Section">
            <section class="s_{config['theme_name']}_cta pt-5 pb-5 o_cc o_cc1">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-8">
                            <h2 class="fw-bold mb-3">Ready to Get Started?</h2>
                            <p class="lead mb-0">Contact us today to learn more about our services.</p>
                        </div>
                        <div class="col-lg-4 text-lg-end mt-4 mt-lg-0">
                            <a href="/contactus" class="btn btn-primary btn-lg">
                                Contact Us
                            </a>
                        </div>
                    </div>
                </div>
            </section>
        </template>

        <!-- Register snippet in builder -->
        <template id="s_{config['theme_name']}_cta_insert" inherit_id="website.snippets">
            <xpath expr="{xpath_target}" position="after">
                <t t-snippet="theme_{config['theme_name']}.s_{config['theme_name']}_cta"
                   string="{config['display_name']} CTA"{group_attr}
                   t-thumbnail="/theme_{config['theme_name']}/static/src/img/snippets/cta_thumb.png"/>
            </xpath>
        </template>
    </data>
</odoo>
'''


def generate_home_page_xml(config):
    """Generate data/pages/home_page.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data noupdate="0">
        <template
            name="{config['display_name']} Home Page"
            id="{config['theme_name']}_home_page"
            inherit_id="website.homepage"
            active="True">
            <xpath expr="//div[@id='wrap']" position="replace">
                <t t-set="is_home_page" t-value="True"/>
                <div id="wrap" class="oe_structure oe_empty">
                    <main class="main__content">
                        <!-- Hero Section -->
                        <section class="s_hero pt-5 pb-5 o_cc o_cc1">
                            <div class="container">
                                <div class="row align-items-center">
                                    <div class="col-lg-6">
                                        <h1 class="display-4 fw-bold mb-4">
                                            Welcome to {config['display_name']}
                                        </h1>
                                        <p class="lead mb-4">
                                            Your compelling tagline goes here.
                                            Describe your unique value proposition.
                                        </p>
                                        <div class="d-flex gap-3 flex-wrap">
                                            <a href="/contactus"
                                               class="btn btn-primary btn-lg">
                                                Get Started
                                            </a>
                                            <a href="/aboutus"
                                               class="btn btn-outline-secondary btn-lg">
                                                Learn More
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 mt-4 mt-lg-0">
                                        <div class="position-relative animate-on-scroll">
                                            <!-- Hero image placeholder -->
                                            <div class="bg-light rounded-3 p-5 text-center">
                                                <i class="fa fa-image fa-5x text-muted"></i>
                                                <p class="mt-3 text-muted">Hero Image</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>

                        <!-- Editable structure for snippets -->
                        <div class="oe_structure"/>

                        <!-- Features Section -->
                        <section class="s_features pt-5 pb-5 o_cc o_cc3">
                            <div class="container">
                                <div class="text-center mb-5">
                                    <h2 class="fw-bold">Our Features</h2>
                                    <p class="text-muted">
                                        Discover what makes us different
                                    </p>
                                </div>
                                <div class="row g-4">
                                    <div class="col-md-4">
                                        <div class="card h-100 border-0 shadow-sm animate-on-scroll">
                                            <div class="card-body text-center p-4">
                                                <div class="feature-icon mb-3">
                                                    <i class="fa fa-star fa-2x text-primary"></i>
                                                </div>
                                                <h5 class="card-title">Feature One</h5>
                                                <p class="card-text text-muted">
                                                    Description of your first amazing feature.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="card h-100 border-0 shadow-sm animate-on-scroll">
                                            <div class="card-body text-center p-4">
                                                <div class="feature-icon mb-3">
                                                    <i class="fa fa-heart fa-2x text-primary"></i>
                                                </div>
                                                <h5 class="card-title">Feature Two</h5>
                                                <p class="card-text text-muted">
                                                    Description of your second great feature.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="card h-100 border-0 shadow-sm animate-on-scroll">
                                            <div class="card-body text-center p-4">
                                                <div class="feature-icon mb-3">
                                                    <i class="fa fa-rocket fa-2x text-primary"></i>
                                                </div>
                                                <h5 class="card-title">Feature Three</h5>
                                                <p class="card-text text-muted">
                                                    Description of your third excellent feature.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>

                        <!-- Editable structure -->
                        <div class="oe_structure"/>
                    </main>
                </div>
            </xpath>
        </template>
    </data>
</odoo>
'''


def generate_about_page_xml(config):
    """Generate data/pages/aboutus_page.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data noupdate="0">
        <!-- About Page View -->
        <template id="{config['theme_name']}_aboutus_view" name="{config['display_name']} About Us">
            <t t-call="website.layout">
                <div id="wrap" class="oe_structure">
                    <main class="main__content">
                        <!-- Page Header -->
                        <section class="s_page_header pt-5 pb-4 o_cc o_cc1">
                            <div class="container">
                                <h1 class="display-5 fw-bold">About Us</h1>
                                <p class="lead">Learn more about our story and mission</p>
                            </div>
                        </section>

                        <!-- About Content -->
                        <section class="s_about_content pt-5 pb-5">
                            <div class="container">
                                <div class="row">
                                    <div class="col-lg-6 mb-4 mb-lg-0">
                                        <h2 class="fw-bold mb-4">Our Story</h2>
                                        <p class="text-muted">
                                            Add your company story here. Tell visitors about
                                            your journey, your values, and what drives you.
                                        </p>
                                        <p class="text-muted">
                                            Share your mission and vision. Explain how you
                                            help your customers and what makes you unique.
                                        </p>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="bg-light rounded-3 p-5 text-center">
                                            <i class="fa fa-building fa-5x text-muted"></i>
                                            <p class="mt-3 text-muted">Company Image</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>

                        <!-- Editable structure -->
                        <div class="oe_structure"/>
                    </main>
                </div>
            </t>
        </template>

        <!-- About Page Record -->
        <record id="page_{config['theme_name']}_aboutus" model="theme.website.page">
            <field name="view_id" ref="{config['theme_name']}_aboutus_view"/>
            <field name="is_published" eval="True"/>
            <field name="url">/aboutus</field>
            <field name="name">About Us</field>
        </record>
    </data>
</odoo>
'''


def generate_contact_page_xml(config):
    """Generate data/pages/contactus_page.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data noupdate="0">
        <!-- Contact Page Customization (inherits from website.contactus) -->
        <template
            id="{config['theme_name']}_contactus"
            inherit_id="website.contactus"
            name="{config['display_name']} Contact">
            <xpath expr="//h1" position="replace">
                <h1 class="display-5 fw-bold">Get in Touch</h1>
            </xpath>
        </template>
    </data>
</odoo>
'''


def generate_services_page_xml(config):
    """Generate data/pages/services_page.xml content"""
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data noupdate="0">
        <!-- Services Page View -->
        <template id="{config['theme_name']}_services_view" name="{config['display_name']} Services">
            <t t-call="website.layout">
                <div id="wrap" class="oe_structure">
                    <main class="main__content">
                        <!-- Page Header -->
                        <section class="s_page_header pt-5 pb-4 o_cc o_cc1">
                            <div class="container">
                                <h1 class="display-5 fw-bold">Our Services</h1>
                                <p class="lead">Discover how we can help you</p>
                            </div>
                        </section>

                        <!-- Services Grid -->
                        <section class="s_services pt-5 pb-5">
                            <div class="container">
                                <div class="row g-4">
                                    <div class="col-md-6 col-lg-4">
                                        <div class="card h-100 border-0 shadow-sm">
                                            <div class="card-body p-4">
                                                <i class="fa fa-cog fa-2x text-primary mb-3"></i>
                                                <h5 class="card-title">Service One</h5>
                                                <p class="card-text text-muted">
                                                    Description of your first service offering.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-lg-4">
                                        <div class="card h-100 border-0 shadow-sm">
                                            <div class="card-body p-4">
                                                <i class="fa fa-chart-line fa-2x text-primary mb-3"></i>
                                                <h5 class="card-title">Service Two</h5>
                                                <p class="card-text text-muted">
                                                    Description of your second service offering.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-lg-4">
                                        <div class="card h-100 border-0 shadow-sm">
                                            <div class="card-body p-4">
                                                <i class="fa fa-users fa-2x text-primary mb-3"></i>
                                                <h5 class="card-title">Service Three</h5>
                                                <p class="card-text text-muted">
                                                    Description of your third service offering.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>

                        <!-- Editable structure -->
                        <div class="oe_structure"/>
                    </main>
                </div>
            </t>
        </template>

        <!-- Services Page Record -->
        <record id="page_{config['theme_name']}_services" model="theme.website.page">
            <field name="view_id" ref="{config['theme_name']}_services_view"/>
            <field name="is_published" eval="True"/>
            <field name="url">/services</field>
            <field name="name">Services</field>
        </record>
    </data>
</odoo>
'''


def generate_gitkeep():
    """Generate .gitkeep content"""
    return ''


def create_theme(config):
    """Create complete theme module"""
    theme_path = create_directory_structure(config['output_path'], config['theme_name'])

    files = {
        '__init__.py': generate_init_py(),
        '__manifest__.py': generate_manifest(config),
        'security/ir.model.access.csv': generate_security_csv(),
        'static/src/scss/primary_variables.scss': generate_primary_variables(config),
        'static/src/scss/bootstrap_overridden.scss': generate_bootstrap_overridden(config),
        'static/src/scss/theme.scss': generate_theme_scss(config),
        'static/src/js/theme.js': generate_theme_js(config),
        'static/src/js/snippets_options.js': generate_snippets_options_js(config),
        'static/src/img/.gitkeep': generate_gitkeep(),
        'data/assets.xml': generate_assets_xml(config),
        'data/menu.xml': generate_menu_xml(config),
        'data/pages/home_page.xml': generate_home_page_xml(config),
        'data/pages/aboutus_page.xml': generate_about_page_xml(config),
        'data/pages/contactus_page.xml': generate_contact_page_xml(config),
        'data/pages/services_page.xml': generate_services_page_xml(config),
        'views/layout/header.xml': generate_header_xml(config),
        'views/layout/footer.xml': generate_footer_xml(config),
        'views/layout/templates.xml': generate_templates_xml(config),
        'views/snippets/custom_snippets.xml': generate_snippets_xml(config),
    }

    created_files = []
    for file_path, content in files.items():
        full_path = theme_path / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding='utf-8')
        created_files.append(file_path)

    return theme_path, created_files


def parse_colors(colors_str):
    """Parse comma-separated color string into dict"""
    if not colors_str:
        return DEFAULT_COLORS.copy()

    colors = colors_str.split(',')
    if len(colors) != 5:
        print(f"Warning: Expected 5 colors, got {len(colors)}. Using defaults.")
        return DEFAULT_COLORS.copy()

    return {
        'color_1': colors[0].strip(),
        'color_2': colors[1].strip(),
        'color_3': colors[2].strip(),
        'color_4': colors[3].strip(),
        'color_5': colors[4].strip(),
    }


def main():
    parser = argparse.ArgumentParser(description='Create Odoo theme module')
    parser.add_argument('theme_name', help='Theme name (will be converted to snake_case)')
    parser.add_argument('output_path', help='Path to create theme in')
    parser.add_argument('--version', type=int, default=17, help='Odoo version (14-19)')
    parser.add_argument('--colors', help='5 hex colors comma-separated')
    parser.add_argument('--font', default='IBM Plex Sans', help='Primary font family')
    parser.add_argument('--header', default='default', help='Header template')
    parser.add_argument('--footer', default='default', help='Footer template')
    parser.add_argument('--author', default='TaqaTechno', help='Author name')

    args = parser.parse_args()

    theme_name = to_snake_case(args.theme_name)
    display_name = to_display_name(theme_name)

    config = {
        'theme_name': theme_name,
        'display_name': display_name,
        'palette_name': f'{theme_name}_colors',
        'output_path': args.output_path,
        'odoo_version': args.version,
        'bootstrap_version': get_bootstrap_version(args.version),
        'colors': parse_colors(args.colors),
        'font': args.font,
        'header_template': args.header,
        'footer_template': args.footer,
        'author': args.author,
    }

    print(f"\n{'='*60}")
    print(f"Creating theme: theme_{theme_name}")
    print(f"Odoo Version: {args.version}")
    print(f"Bootstrap: {config['bootstrap_version']}")
    print(f"{'='*60}\n")

    theme_path, created_files = create_theme(config)

    print(f"\n{'='*60}")
    print(f"THEME CREATED SUCCESSFULLY!")
    print(f"{'='*60}")
    print(f"Location: {theme_path}")
    print(f"\nFiles created:")
    for f in created_files:
        print(f"  [OK] {f}")

    print(f"\n{'='*60}")
    print("NEXT STEPS:")
    print(f"{'='*60}")
    print(f"1. Update module list:")
    print(f"   python -m odoo -c conf/<config>.conf -d <db> --update-list")
    print(f"\n2. Install theme:")
    print(f"   python -m odoo -c conf/<config>.conf -d <db> -i theme_{theme_name} --stop-after-init")
    print(f"\n3. Activate theme:")
    print(f"   Website > Configuration > Settings > Theme")
    print(f"{'='*60}\n")

    return 0


if __name__ == '__main__':
    sys.exit(main())
